backup_restore_register_to_index

diff --git a/server b/server
--- a/server
+++ b/server
@@ -64,6 +64,79 @@ restart)
   ./server start
   
   ;;
+status)
+  freemem=$(free -m | grep "Mem:" | awk '{print $4}')
+  echo $Y"Memory Available: ${freemem} MB"${W}
+
+  ;;
+backup)
+  echo $P"CREATING BACKUP!"$W
+
+	echo "Please Enter PostgreSQL Password:"
+	read db_pwd
+  export PGPASSWORD=$db_pwd
+
+  folder_name=backup_$(date +%Y_%m_%d_%H_%M_%S)
+  mkdir /root/gf_server/backup/$folder_name
+
+	echo "Creating gf_gs backup"
+  pg_dump -U postgres -Fp gf_gs > /root/gf_server/backup/$folder_name/gf_gs.sql
+
+	echo "Creating gf_ls backup"
+  pg_dump -U postgres -Fp gf_ls > /root/gf_server/backup/$folder_name/gf_ls.sql
+
+	echo "Creating gf_ms backup"
+  pg_dump -U postgres -Fp gf_ms > /root/gf_server/backup/$folder_name/gf_ms.sql
+
+  chmod -R 777 /root
+
+  echo $B"BACKUP CREATED! > $folder_name"$W
+
+  ;;
+restore)
+  echo $P"RESTORING BACKUP!"$W
+
+  if [ -z "$2" ]; then
+    echo "Please Use: ./server restore <folder name ex: backup_2023_01_17_02_55_10>"
+    exit 1
+  fi
+
+  if [ ! -d "/root/gf_server/backup/$2" ]; then
+    echo "Backup Folder Not Found"
+    exit 1
+  fi
+
+  if [ $(find /root/gf_server/backup/$2 -name "gf_gs.sql" -o -name "gf_ls.sql" -o -name "gf_ms.sql" | wc -l) -ne 3 ]; then
+    echo "Some Backup Files 'gf_gs.sql, gf_ls.sql, gf_ms.sql' Not Found!"
+    exit 1
+  fi
+
+	echo "Please Enter PostgreSQL Password:"
+	read db_pwd
+  export PGPASSWORD=$db_pwd
+
+  folder_name=$2
+
+	echo "Restoring gf_gs backup"
+	psql -U postgres -c "DROP DATABASE gf_gs;"
+	psql -U postgres -c "create database gf_gs encoding 'UTF8' template template0;"
+  psql -U postgres -d gf_gs -f /root/gf_server/backup/$folder_name/gf_gs.sql
+
+	echo "Restoring gf_ls backup"
+	psql -U postgres -c "DROP DATABASE gf_ls;"
+  psql -U postgres -c "create database gf_ls encoding 'UTF8' template template0;"
+  psql -U postgres -d gf_ls -f /root/gf_server/backup/$folder_name/gf_ls.sql
+
+	echo "Restoring gf_ms backup"
+	psql -U postgres -c "DROP DATABASE gf_ms;"
+  psql -U postgres -c "create database gf_ms encoding 'UTF8' template template0;"
+  psql -U postgres -d gf_ms -f /root/gf_server/backup/$folder_name/gf_ms.sql
+
+  chmod -R 777 /root
+
+  echo $B"BACKUP RESTORATION DONE! > $folder_name"$W
+
+  ;;
 clear)
   echo $P"CLEANING LOGS!"$W
   cat /dev/null >/var/log/syslog
@@ -78,7 +151,14 @@ clear)
 
   ;;
 *)
-  echo "Usage: $0 {start|stop|restart|clear}"
+  echo "Usage: $0 {start|stop|restart|status|backup|restore|clear}"
+  echo "start - Start Sever"
+  echo "stop - Stop Server"
+  echo "restart - Restart Server"
+  echo "status - Show Server Memory Usage"
+  echo "backup - Create DB backup 'gf_gs, gf_ls, gf_ms'"
+  echo "restore - Restore Backup  |Usage: ./server restore <folder name ex: backup_2023_01_17_02_55_10>"
+  echo "clear - Clear Server Logs"
   exit 1
   ;;
 esac
